### ISSUE TITLE
Nokia 6.2 (SLD_sprout) wifi not working 

### ISSUE THREAD

**Issue by Tauin-zz** [TeamWin/android_device_nokia_SLD_sprout#1]
- [ Y ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ Y ] I am running the latest version of TWRP
- [ Y ] I have read the FAQ (https://twrp.me/FAQ/)
- [ Y ] I have searched for my issue and it does not already exist

**Device codename**: 
**TWRP version**: 

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?

1] Install TWRP using method found on the nokia 6.2 TWRP website https://twrp.me/nokia/nokia6.2.html
2] reboot into android system

#### WHAT IS THE EXPECTED RESULT?

Wifi turning on and working as expected

#### WHAT HAPPENS INSTEAD?

Wifi cannot turn on and connect, turns off after failing.

#### ADDITIONAL INFORMATION

Everything else works in the notification center (Bluetooth, 4G etc etc), wifi also does not turn on using settings menu.

`/tmp/recovery.log`: 
`dmesg`:

**Comment by RaghuVarma331** [comment]
Hello there thanks for the bug report
Well , you are right wifi never work until we patch our kernel sources with proper wlan drivers from Qualcomm but as far as we know we don't have proper kernel sources support from nokia
Especially because of the phones which got shipped with bootloader unlockable by default & iam just managing with prebuilt kernel infact we will never get kernel sources especially for Nokia 7.2 & 6.2

**Comment by RaghuVarma331** [comment]
Thanks
